### ISSUE TITLE
cfmongodb.lib.javaloader.JavaLoader Case-sensitivity

### ISSUE THREAD

**Issue by aqlong** [marcesher/cfmongodb#16]
Hey Marc,

Great job! Loving it so far. <-- that's not the bug ;)

In JavaloaderFactory.cfc, when it calls cfmongodb.lib.javaloader.javaloader, on CentOS 5.4 64-bit, I was getting an error that it couldn't be found. 

So, I fixed the case to match the file name (cfmongodb.lib.javaloader.JavaLoader), and it worked. Strange thing is that it worked on my local CentOS 5.4 VM, but not on live, and a best I can tell they're exactly the same. But it's probably over my head, and the point is that when the case matched, it worked great, and so I imagine it's an easy fix :)

Peace bro

**Comment by marcesher** [comment]
thanks!
