### ISSUE TITLE
$inc not working

### ISSUE THREAD

**Issue by bimp** [marcesher/cfmongodb#20]
Downloaded, installed, configured CFMongoDB into my prototype 
application and all the examples work in /examples/gettingstarted.cfm 
EXCEPT for the $inc example:

```
    //perform an $inc update???? Doesn't work?? 
    cast = [{NAME = "Wesley", LIFELEFT=50, TORTUREMACHINE=true}, 
            {NAME = "Spaniard", LIFELEFT=42, TORTUREMACHINE=false}, 
            {NAME = "Giant", LIFELEFT=6, TORTUREMACHINE=false}, 
            {NAME = "Poor Forest Walker", LIFELEFT=60, TORTUREMACHINE=true}]; 
    people.saveAll( cast ); 
    suckLifeOut = {"$inc" = {LIFELEFT = -1}}; 
    victims = {TORTUREMACHINE = true}; 
    people.update( doc = suckLifeOut, query = victims, multi = true ); 
    rugenVictims = people.query().$eq("TORTUREMACHINE", 
```

true).find().asArray(); 
        writeOutput("<h2>Atomically incrementing with $inc</h2>"); 
        writeDump( var = cast, label="Before the movie started", 
expand=false); 
        writeDump( var = rugenVictims, label="Instead of sucking water, I'm 
sucking life", expand=false); 

When I ran it, the writeDump output for the result didn't show the 
LIFELEFT value decreasing by 1. It actually shows the data {"$inc" = 
{LIFELEFT = -1} being added as a new property into the targeted 
documents. I also verified by querying MongoDB directly as so and got the 
following result: 

> db.people.find({"TORTUREMACHINE":true}) 

{ "$inc" : { "LIFELEFT" : -1 }, "LIFELEFT" : 50, "NAME" : "Wesley", 
"TORTUREMACHINE" : true, "_id" : 
ObjectId("4e47048b5ba833d562a1f8d9") } 
{ "$inc" : { "LIFELEFT" : -1 }, "LIFELEFT" : 60, "NAME" : "Poor Forest 
Walker", "TORTUREMACHINE" : true, "_id" : 
ObjectId("4e47048b5ba833d562a1f8dc") }

**Comment by marcesher** [comment]
fixed.
