### ISSUE TITLE
Case inSensitivity in SearchBuilder like() and regex()

### ISSUE THREAD

**Issue by sjdaniels** [marcesher/cfmongodb#29]
I'm working on a pull request adding the ability to do case insensitive queries in SearchBuilder. I'd like your opinion. I'm basically planning on adding regexnocase() for this, and I could also add likenocase(), but my preference would be to make like() itself case-insensitive.

What do you think?

**Comment by marcesher** [comment]
I'm leary of making like() case-insensitive, as it changes mongo's default behavior. as for Regex, if you wanted case insensitivity couldn't you just pass in the "/i" flag as part of your regex?

**Comment by sjdaniels** [comment]
I was unable to figure out how to use /i as a flag, perhaps I was doing it wrong. The only way I could figure out how to make it case-insensitive was to explicitly call pattern.compile() with the CASE_INSENSITIVE flag:

builder.add( element, pattern.compile(regex, pattern.CASE_INSENSITIVE) );

I'm fine with keeping like() as is. And if you have a sec to show me some sample code using the /i flag that would be excellent. Thanks!

**Comment by marcesher** [comment]
Sean,

Thanks for the response, and sorry it's taken me so long to get back. I'm
heading out of town for the next several days, and when I return I'll get
back to this!

marc

**Comment by sjdaniels** [comment]
Hey Marc, I submitted a pull request for a different approach to this, which I think satisfies your desire to keep it on par with Mongo's default behavior. I'll close this, feel free to continue this discussion though.
