### ISSUE TITLE
Finish aggregate()

### ISSUE THREAD

**Issue by marcesher** [marcesher/cfmongodb#34]
1) get rid of mongodb.command() and use the DBCollection.aggregate() method
2) return a proper result object which essentially mimics the AggregationOutput object
3) tests... must cover single pipeline operation, multiple pipeline operations, failures
4) update aggregation/aggregate.cfm

**Comment by marcesher** [comment]
Done. Tests live in AggregationTest.cfc. Examples live in aggregation/aggregate.cfm

**Comment by sjdaniels** [comment]
Thanks for wrapping this up dude! And sorry about all those key:val that should have been key=val :)

I'm so Railo-centric these days...
